# Use Python 3.11 slim image as base
FROM python:3.11-slim

# Set working directory
WORKDIR /app


# Copy requirements first to leverage Docker cache
COPY requirements.txt .

# Install Python dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Copy the rest of the application
COPY . .

# Expose the port Streamlit runs on
EXPOSE 8501

# Set environment variables
ENV PYTHONUNBUFFERED=1 \
    PYTHONDONTWRITEBYTECODE=1 \
    API_URL=http://server:8000

# Command to run the application
CMD ["streamlit", "run", "app.py", "--server.address", "0.0.0.0"] 