version: '3.8'

services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
    environment:
      - API_URL=http://server:8000
    depends_on:
      - server
    networks:
      - rag-network

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - ./server/app/.env
    volumes:
      - qdrant_data:/app/data/qdrant
    networks:
      - rag-network

networks:
  rag-network:
    driver: bridge

volumes:
  qdrant_data:
